// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bot/create": {
            "post": {
                "description": "创建一个新的机器人角色，包含名称、描述和引用的会话ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BotRole"
                ],
                "summary": "创建机器人角色",
                "parameters": [
                    {
                        "description": "机器人角色信息",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.BotRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功创建的机器人角色",
                        "schema": {
                            "$ref": "#/definitions/schema.BotRole"
                        }
                    }
                }
            }
        },
        "/bot/list": {
            "get": {
                "description": "获取所有机器人角色的列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BotRole"
                ],
                "summary": "获取机器人角色列表",
                "responses": {
                    "200": {
                        "description": "机器人角色列表",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/schema.BotRole"
                            }
                        }
                    }
                }
            }
        },
        "/bot/{id}": {
            "get": {
                "description": "根据ID获取指定的机器人角色信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BotRole"
                ],
                "summary": "获取机器人角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "机器人角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "机器人角色信息",
                        "schema": {
                            "$ref": "#/definitions/schema.BotRole"
                        }
                    }
                }
            }
        },
        "/bot/{id}/delete": {
            "post": {
                "description": "删除指定ID的机器人角色",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BotRole"
                ],
                "summary": "删除机器人角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "机器人角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "type": "boolean"
                        }
                    }
                }
            }
        },
        "/bot/{id}/update": {
            "post": {
                "description": "更新指定ID的机器人角色信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BotRole"
                ],
                "summary": "更新机器人角色",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "机器人角色ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "更新的机器人角色信息",
                        "name": "role",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.BotRole"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新后的机器人角色信息",
                        "schema": {
                            "$ref": "#/definitions/schema.BotRole"
                        }
                    }
                }
            }
        },
        "/chat/completion/stream/{session_id}": {
            "post": {
                "description": "流式输出聊天",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "text/event-stream"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "流式输出聊天",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "用户输入及参数",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chat.CompletionStream.userInput"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/chat/config/bots": {
            "get": {
                "description": "获取 bot 角色配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取 bot 角色配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-array_schema_BotRole"
                        }
                    }
                }
            }
        },
        "/chat/config/models": {
            "get": {
                "description": "获取模型配置",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "config"
                ],
                "summary": "获取模型配置",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-array_schema_ModelCache"
                        }
                    }
                }
            }
        },
        "/chat/message/list/{session_id}": {
            "get": {
                "description": "获取消息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Message"
                ],
                "summary": "获取消息",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页参数",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort_expr",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-entity_PaginatedContinuationResponse-schema_Message"
                        }
                    }
                }
            }
        },
        "/chat/session/del/{session_id}": {
            "post": {
                "description": "删除会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "删除会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-bool"
                        }
                    }
                }
            }
        },
        "/chat/session/list": {
            "get": {
                "description": "获取会话列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "获取会话列表",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页参数",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort_expr",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-entity_PaginatedContinuationResponse-schema_UserSession"
                        }
                    }
                }
            }
        },
        "/chat/session/new": {
            "post": {
                "description": "创建会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "创建会话",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-string"
                        }
                    }
                }
            }
        },
        "/chat/session/share/{session_id}": {
            "post": {
                "description": "分享会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "分享会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "分享信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/chat.ShareSession.ShareRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-bool"
                        }
                    }
                }
            }
        },
        "/chat/session/sync": {
            "get": {
                "description": "同步会话列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "同步会话列表",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "客户端上次同步时间戳",
                        "name": "last_sync_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "分页参数",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-entity_PaginatedSyncListResponse-schema_UserSession"
                        }
                    }
                }
            }
        },
        "/chat/session/update/{session_id}": {
            "post": {
                "description": "更新会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "更新会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "会话信息",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.Session"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-bool"
                        }
                    }
                }
            }
        },
        "/chat/session/user/{session_id}": {
            "get": {
                "description": "获取用户会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "获取用户会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_UserSession"
                        }
                    }
                }
            }
        },
        "/chat/session/{session_id}": {
            "get": {
                "description": "获取会话",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Session"
                ],
                "summary": "获取会话",
                "parameters": [
                    {
                        "type": "string",
                        "description": "会话 ID",
                        "name": "session_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Session"
                        }
                    }
                }
            }
        },
        "/manage/provider/create": {
            "post": {
                "description": "创建 API 提供商",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "创建 API 提供商",
                "parameters": [
                    {
                        "description": "API 提供商参数",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.Provider"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功创建的 API 提供商",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Provider"
                        }
                    }
                }
            }
        },
        "/manage/provider/delete/{provider_id}": {
            "post": {
                "description": "删除 API 提供商",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "删除 API 提供商",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "API 提供商 ID",
                        "name": "provider_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功与否",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-bool"
                        }
                    }
                }
            }
        },
        "/manage/provider/list": {
            "get": {
                "description": "批量获取 API 提供商",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "批量获取 API 提供商",
                "responses": {
                    "200": {
                        "description": "API 提供商列表",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-array_schema_Provider"
                        }
                    }
                }
            }
        },
        "/manage/provider/update": {
            "post": {
                "description": "更新 API 提供商",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "更新 API 提供商",
                "parameters": [
                    {
                        "description": "API 提供商参数",
                        "name": "provider",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.Provider"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功与否",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-bool"
                        }
                    }
                }
            }
        },
        "/manage/provider/{provider_id}": {
            "get": {
                "description": "获取 API 提供商",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Provider"
                ],
                "summary": "获取 API 提供商",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "API 提供商 ID",
                        "name": "provider_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "API 提供商",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Provider"
                        }
                    }
                }
            }
        },
        "/tue/course/create": {
            "post": {
                "description": "创建课程基础参数，绑定或创建题目、资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course"
                ],
                "summary": "创建课程",
                "parameters": [
                    {
                        "description": "课程内容",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.Course"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Course"
                        }
                    }
                }
            }
        },
        "/tue/course/list": {
            "get": {
                "description": "获取课程列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course"
                ],
                "summary": "获取课程列表",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页参数",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort_expr",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-entity_PaginatedTotalResponse-schema_Course"
                        }
                    }
                }
            }
        },
        "/tue/course/update": {
            "post": {
                "description": "更新课程基础参数，增量更新 题目、资源",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course"
                ],
                "summary": "更新课程",
                "parameters": [
                    {
                        "description": "课程内容",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.Course"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Course"
                        }
                    }
                }
            }
        },
        "/tue/course/{id}": {
            "get": {
                "description": "获取单个课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course"
                ],
                "summary": "获取单个课程",
                "parameters": [
                    {
                        "type": "string",
                        "description": "课程 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Course"
                        }
                    }
                }
            },
            "post": {
                "description": "删除课程",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Course"
                ],
                "summary": "删除课程",
                "parameters": [
                    {
                        "type": "string",
                        "description": "课程 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-any"
                        }
                    }
                }
            }
        },
        "/tue/exam/create": {
            "get": {
                "description": "保存单个测验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exam"
                ],
                "summary": "保存单个测验",
                "parameters": [
                    {
                        "description": "测验内容",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.Exam"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Exam"
                        }
                    }
                }
            }
        },
        "/tue/exam/{id}": {
            "get": {
                "description": "获取单个测验",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Exam"
                ],
                "summary": "获取单个测验",
                "parameters": [
                    {
                        "type": "string",
                        "description": "测验 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Exam"
                        }
                    }
                }
            }
        },
        "/tue/problem/create": {
            "post": {
                "description": "创建单个题目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Problem"
                ],
                "summary": "创建单个题目",
                "parameters": [
                    {
                        "description": "题目结构",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.Problem"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Problem"
                        }
                    }
                }
            }
        },
        "/tue/problem/list": {
            "get": {
                "description": "分页获取题目列表",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Problem"
                ],
                "summary": "分页获取题目列表",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "end_time",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "分页参数",
                        "name": "page_num",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "sort_expr",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "start_time",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-entity_PaginatedContinuationResponse-schema_Problem"
                        }
                    }
                }
            }
        },
        "/tue/problem/{id}": {
            "get": {
                "description": "获取单个题目",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Problem"
                ],
                "summary": "获取单个题目",
                "parameters": [
                    {
                        "type": "string",
                        "description": "题目 ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回数据",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_Problem"
                        }
                    }
                }
            }
        },
        "/user/login": {
            "post": {
                "description": "用户登录",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用户登录",
                "parameters": [
                    {
                        "description": "登录请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.Login.loginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "login successfully",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_User"
                        }
                    }
                }
            }
        },
        "/user/logout": {
            "post": {
                "description": "用户登出",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用户登出",
                "responses": {}
            }
        },
        "/user/ping": {
            "post": {
                "description": "检测客户端登录态",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "检测客户端登录态",
                "responses": {
                    "200": {
                        "description": "user is online",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-schema_User"
                        }
                    },
                    "404": {
                        "description": "user not found",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-any"
                        }
                    }
                }
            }
        },
        "/user/refresh": {
            "get": {
                "description": "刷新登录态",
                "tags": [
                    "User"
                ],
                "summary": "刷新登录态",
                "parameters": [
                    {
                        "type": "string",
                        "description": "刷新用 Token",
                        "name": "X-Refresh-Token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "nothing",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "用户注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "用户注册",
                "parameters": [
                    {
                        "description": "注册请求",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.Register.registerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "register successfully",
                        "schema": {
                            "$ref": "#/definitions/entity.CommonResponse-bool"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "chat.CompletionStream.userInput": {
            "type": "object",
            "required": [
                "model_name",
                "provider_name",
                "question"
            ],
            "properties": {
                "bot_id": {
                    "type": "integer"
                },
                "enable_context": {
                    "type": "boolean"
                },
                "model_name": {
                    "description": "Model.Name 准确的模型名称",
                    "type": "string"
                },
                "provider_name": {
                    "description": "Provider.Name 准确的供应商名称",
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "system_prompt": {
                    "description": "系统提示词",
                    "type": "string"
                }
            }
        },
        "chat.ShareSession.ShareRequest": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "share_info": {
                    "$ref": "#/definitions/schema.ShareInfo"
                }
            }
        },
        "entity.CommonResponse-any": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据"
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-array_schema_BotRole": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.BotRole"
                    }
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-array_schema_ModelCache": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.ModelCache"
                    }
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-array_schema_Provider": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Provider"
                    }
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-bool": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "boolean"
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-entity_PaginatedContinuationResponse-schema_Message": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.PaginatedContinuationResponse-schema_Message"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-entity_PaginatedContinuationResponse-schema_Problem": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.PaginatedContinuationResponse-schema_Problem"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-entity_PaginatedContinuationResponse-schema_UserSession": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.PaginatedContinuationResponse-schema_UserSession"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-entity_PaginatedSyncListResponse-schema_UserSession": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.PaginatedSyncListResponse-schema_UserSession"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-entity_PaginatedTotalResponse-schema_Course": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/entity.PaginatedTotalResponse-schema_Course"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-schema_Course": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Course"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-schema_Exam": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Exam"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-schema_Problem": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Problem"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-schema_Provider": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Provider"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-schema_Session": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Session"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-schema_User": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.User"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-schema_UserSession": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.UserSession"
                        }
                    ]
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.CommonResponse-string": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "代码",
                    "type": "integer"
                },
                "data": {
                    "description": "数据",
                    "type": "string"
                },
                "msg": {
                    "description": "消息",
                    "type": "string"
                }
            }
        },
        "entity.PaginatedContinuationResponse-schema_Message": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Message"
                    }
                },
                "next_page": {
                    "type": "integer"
                }
            }
        },
        "entity.PaginatedContinuationResponse-schema_Problem": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Problem"
                    }
                },
                "next_page": {
                    "type": "integer"
                }
            }
        },
        "entity.PaginatedContinuationResponse-schema_UserSession": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.UserSession"
                    }
                },
                "next_page": {
                    "type": "integer"
                }
            }
        },
        "entity.PaginatedSyncListResponse-schema_UserSession": {
            "type": "object",
            "properties": {
                "deleted": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.UserSession"
                    }
                },
                "next_page": {
                    "type": "integer"
                },
                "updated": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.UserSession"
                    }
                }
            }
        },
        "entity.PaginatedTotalResponse-schema_Course": {
            "type": "object",
            "properties": {
                "last_page": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Course"
                    }
                }
            }
        },
        "schema.APIKey": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "description": "API 密钥",
                    "type": "string"
                },
                "provider_id": {
                    "description": "外键，指向 Provider",
                    "type": "integer"
                }
            }
        },
        "schema.BotRole": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "角色描述",
                    "type": "string"
                },
                "id": {
                    "description": "原始数据",
                    "type": "integer"
                },
                "name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "prompt_session": {
                    "description": "组装数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Session"
                        }
                    ]
                },
                "prompt_session_id": {
                    "description": "引用一个 session 中的对话作为 prompt",
                    "type": "string"
                }
            }
        },
        "schema.Course": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "课程描述",
                    "type": "string"
                },
                "exams": {
                    "description": "课程考试",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.CourseExam"
                    }
                },
                "id": {
                    "description": "原始数据",
                    "type": "integer"
                },
                "name": {
                    "description": "课程名称",
                    "type": "string"
                },
                "resources": {
                    "description": "关联数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.CourseResource"
                    }
                },
                "sorted_data": {
                    "description": "排好序的数据",
                    "type": "array",
                    "items": {}
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schema.CourseExam": {
            "type": "object",
            "properties": {
                "course_id": {
                    "description": "关联课程ID",
                    "type": "integer"
                },
                "exam": {
                    "description": "考试详细信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Exam"
                        }
                    ]
                },
                "exam_id": {
                    "description": "关联考试ID",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "sort_order": {
                    "description": "考试排序",
                    "type": "integer"
                }
            }
        },
        "schema.CourseResource": {
            "type": "object",
            "properties": {
                "course_id": {
                    "description": "关联课程ID",
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "resource": {
                    "description": "资源详细信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Resource"
                        }
                    ]
                },
                "resource_id": {
                    "description": "关联资源ID",
                    "type": "integer"
                },
                "sort_order": {
                    "description": "资源排序",
                    "type": "integer"
                }
            }
        },
        "schema.Exam": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "考试描述",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "problems": {
                    "description": "考试包含的大题",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.ExamProblem"
                    }
                },
                "subjects": {
                    "description": "所属科目分类",
                    "type": "string"
                },
                "total_score": {
                    "description": "考试总分（单位：0.01分）",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schema.ExamProblem": {
            "type": "object",
            "properties": {
                "exam_id": {
                    "description": "关联考试ID",
                    "type": "integer"
                },
                "problem": {
                    "description": "题目详细信息",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Problem"
                        }
                    ]
                },
                "problem_id": {
                    "description": "关联题目ID",
                    "type": "integer"
                },
                "score": {
                    "description": "题目分值（1表示0.01分）",
                    "type": "integer"
                },
                "sort_order": {
                    "description": "题目排序",
                    "type": "integer"
                }
            }
        },
        "schema.Message": {
            "type": "object",
            "properties": {
                "bot_role": {
                    "$ref": "#/definitions/schema.BotRole"
                },
                "bot_role_id": {
                    "description": "回复所使用的模型",
                    "type": "integer"
                },
                "content": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "description": "默认结构",
                    "type": "integer"
                },
                "model": {
                    "description": "组装结构",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Model"
                        }
                    ]
                },
                "model_id": {
                    "description": "回复所使用的模型",
                    "type": "integer"
                },
                "reasoning_content": {
                    "type": "string"
                },
                "role": {
                    "description": "user/assistant/system",
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "token_usage": {
                    "type": "integer"
                }
            }
        },
        "schema.Model": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "使用 JSON 储存配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.ModelConfig"
                        }
                    ]
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "额外模型描述",
                    "type": "string"
                },
                "display_name": {
                    "description": "对外展示模型名称",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "模型名称",
                    "type": "string"
                },
                "provider_id": {
                    "description": "关联的 Provider ID",
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schema.ModelCache": {
            "type": "object",
            "properties": {
                "config": {
                    "description": "使用 JSON 储存配置",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.ModelConfig"
                        }
                    ]
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "额外模型描述",
                    "type": "string"
                },
                "display_name": {
                    "description": "对外展示模型名称",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "模型名称",
                    "type": "string"
                },
                "provider_display_name": {
                    "description": "关联的 Provider DisplayName",
                    "type": "string"
                },
                "provider_id": {
                    "description": "关联的 Provider ID",
                    "type": "integer"
                },
                "provider_name": {
                    "description": "关联的 Provider FileName",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schema.ModelConfig": {
            "type": "object",
            "properties": {
                "allow_system_prompt": {
                    "description": "是否允许用户自行修改系统提示",
                    "type": "boolean"
                },
                "default_temperature": {
                    "description": "默认温度",
                    "type": "number"
                },
                "frequency_penalty": {
                    "type": "number"
                },
                "max_tokens": {
                    "type": "integer"
                },
                "presence_penalty": {
                    "type": "number"
                },
                "system_prompt": {
                    "description": "预设系统提示",
                    "type": "string"
                },
                "top_p": {
                    "type": "number"
                }
            }
        },
        "schema.Permission": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "权限描述",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "module": {
                    "description": "所属模块（handler名称）",
                    "type": "string"
                },
                "name": {
                    "description": "权限名称",
                    "type": "string"
                },
                "path": {
                    "description": "权限路径（形如：POST:/user/create）",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schema.Problem": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "答案（JSON存储ProblemAnswer）",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.ProblemAnswer"
                        }
                    ]
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "支持HTML/Markdown",
                    "type": "string"
                },
                "difficulty": {
                    "description": "难度等级 1-5",
                    "type": "integer"
                },
                "explanation": {
                    "description": "答案解析",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "options": {
                    "description": "选项（JSON存储ProblemOption数组）",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.ProblemOption"
                    }
                },
                "subject": {
                    "description": "所属科目/分类",
                    "type": "string"
                },
                "type": {
                    "$ref": "#/definitions/schema.ProblemType"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schema.ProblemAnswer": {
            "type": "object",
            "properties": {
                "answer": {
                    "description": "选择题：存储正确选项ID []uint\n填空题：存储多个填空关键词 []string\n判断题：true/false\n简答题：文本答案 string"
                }
            }
        },
        "schema.ProblemOption": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "correct": {
                    "description": "是否正确答案",
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "schema.ProblemType": {
            "type": "string",
            "enum": [
                "single_choice",
                "multiple_choice",
                "fill_blank",
                "short_answer",
                "true_false"
            ],
            "x-enum-varnames": [
                "SingleChoice",
                "MultipleChoice",
                "FillBlank",
                "ShortAnswer",
                "TrueFalse"
            ]
        },
        "schema.Provider": {
            "type": "object",
            "properties": {
                "api_keys": {
                    "description": "一对多关系，与 APIKey 模型关联",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.APIKey"
                    }
                },
                "base_url": {
                    "description": "API 的基本 URL",
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "额外提供商描述",
                    "type": "string"
                },
                "display_name": {
                    "description": "对外展示提供商名称",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "提供商名称",
                    "type": "string"
                },
                "schema": {
                    "description": "一对多关系，与 Model 模型关联",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Model"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schema.Resource": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "资源描述",
                    "type": "string"
                },
                "file_key": {
                    "description": "文件的 uuid key",
                    "type": "string"
                },
                "file_name": {
                    "description": "OSS 中的文件名",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "origin_file_name": {
                    "description": "原始文件名",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schema.Role": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "description": "角色描述",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "description": "角色名称",
                    "type": "string"
                },
                "permissions": {
                    "description": "多对多关联",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Permission"
                    }
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "schema.Session": {
            "type": "object",
            "properties": {
                "context_size": {
                    "description": "上下文大小",
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "enable_context": {
                    "description": "上下文开关",
                    "type": "boolean"
                },
                "id": {
                    "description": "原始数据",
                    "type": "string"
                },
                "last_active": {
                    "type": "string"
                },
                "messages": {
                    "description": "组装数据",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Message"
                    }
                },
                "name": {
                    "type": "string"
                },
                "system_prompt": {
                    "description": "系统提示词",
                    "type": "string"
                }
            }
        },
        "schema.ShareInfo": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "邀请码（可选）",
                    "type": "string"
                },
                "expired_at": {
                    "description": "邀请过期时间",
                    "type": "integer"
                },
                "permanent": {
                    "description": "是否永久分享",
                    "type": "boolean"
                },
                "title": {
                    "description": "分享标题",
                    "type": "string"
                }
            }
        },
        "schema.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "roles": {
                    "description": "用户与角色之间的多对多关系",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/schema.Role"
                    }
                },
                "updated_at": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "schema.UserSession": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "session": {
                    "description": "组装数据",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.Session"
                        }
                    ]
                },
                "session_id": {
                    "type": "string"
                },
                "share_info": {
                    "description": "分享字段",
                    "allOf": [
                        {
                            "$ref": "#/definitions/schema.ShareInfo"
                        }
                    ]
                },
                "type": {
                    "$ref": "#/definitions/schema.UserSessionType"
                },
                "user_id": {
                    "description": "原始数据",
                    "type": "integer"
                }
            }
        },
        "schema.UserSessionType": {
            "type": "integer",
            "enum": [
                1,
                2
            ],
            "x-enum-varnames": [
                "OWNER",
                "INVITEE"
            ]
        },
        "user.Login.loginRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "user.Register.registerRequest": {
            "type": "object",
            "required": [
                "password",
                "username"
            ],
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
